thaiRock = [
    'Big Ass - ข้าน้อยสมควรตาย',
    'TaitosmitH - นักเลงเก่า (เพลงประกอบภาพยนตร์ 4 KINGS)',
    'Big Ass - คนไม่เอาถ่าน',
    'Silly Fools - จิ๊จ๊ะ',
    'Bodyslam - เรือเล็กควรออกจากฝั่ง',
    'Slot Machine - เพียงไว้ใจ (Theme From KinnPorsche The Series)',
    'Pang Nakarin - ภูมิแพ้กรุงเทพ',
    'Palmy - อยากร้องดังดัง',
    'Bodyslam - คิดฮอด',
    'Bodyslam - อกหัก',
    'Bodyslam - ความเชื่อ',
    'KLEAR - จะรักหรือจะร้าย',
    'Loso - อะไรก็ยอม',
    'F.HERO - มีแค่เรา',
    'YOUNGOHM - ธารารัตน์',
    'Joey Boy - คนโสดในคอนเสิร์ต',
    'P-Hot - Bye Bye',
    'OG-ANIC - เป็นไรไหม?',
    'F.HERO - คอแห้ง',
    '321 - แค่ที่รัก',
    'TaitosmitH - Pattaya Lover',
    'Slot Machine - AI (feat. Violette Wautier)',
    'Da Endorphine - ไม่รู้จักฉัน ไม่รู้จักเธอ',
    'JOEY PHUWASIT - นิดหน่อย',
    'Paper Planes - ทรงอย่างแบด',
    'Getsunova - แตกต่างเหมือนกัน',
    '25 hours - วุ่นวาย',
    'อ๊อฟ Big Ass - ทุ้มอยู่ในใจ - เพลงประกอบภาพยนตร์ "SuckSeed ห่วยขั้นเทพ"',
    'Paper Planes - เสแสร้ง (feat. MOON)',
    'Bodyslam - ย้ำ',
    'P9d - Por Mueng Tai',
    'P-Hot - รำวงในดงชบา'
]

thaiPOP = [
    'Bear Knuckle - DONG',
    'SPRITE - ทน',
    'Tilly Birds - เพื่อนเล่น ไม่เล่นเพื่อน (Just Being Friendly)',
    '25 hours - ยินดีที่ไม่รู้จัก (เพลงประกอบภาพยนตร์ กวน มึน โฮ)',
    'Silly Fools - ขี้หึง',
    'Ice Paris - รักติดไซเรน (My Ambulance) - From รักฉุดใจนายฉุกเฉิน Original Soundtrack',
    'Big Ass - เล่นของสูง',
    'JOEY PHUWASIT - ROCKET FESTIVAL (สัญญาเดือนหก)',
    'URBOYTJ - เค้าก่อน',
    'Three Man Down - วันเกิดฉันปีนี้ (HBD to me)',
    'F.HERO - เสือสิ้นลาย',
    'Buddha Bless - ชิงหมาเกิด',
    'NONT TANONT - พิง (เพลงประกอบละคร กระเช้าสีดา)',
    'Pop Pongkool - Undo',
    'Violette Wautier - จังหวะจะรัก',
    'URBOYTJ - ถามคำ',
    '321 - แค่ที่รัก',
    'URBOYTJ - วายร้าย',
    'Ink Waruntorn - สายตาหลอกกันไม่ได้ (Eyes Don’t Lie)',
    'Bow Maylada - เเฟนผมน่ารัก',
    'Three Man Down - น้อง (Nong)',
    'Singto Numchok - เธอคือของขวัญ',
    'MEYOU - อิจฉา',
    'MEYOU - วันนี้ปีที่แล้ว',
    'Big Ass - ดีแต่ปาก',
    'Lipta - ทักครับ',
    'Singto Numchok - อยู่ต่อเลยได้ไหม',
    'Slot Machine - จันทร์เจ้า (Goodbye)',
    'JOEY PHUWASIT - นะหน้าทอง',
    'Palmy - ดวงใจ',
    'THE TOYS - หน้าหนาวที่แล้ว',
    'Room 39 - ความจริง',
    '25 hours - ไม่เคย',
    'PAPER - ท้องฟ้า',
    'Slot Machine - ผ่าน',
    'LADIIPRANG - โลกเอียง (LOVE MOMENTUM)',
    'BOWKYLION - วาดไว้',
    'Getsunova - ไกลแค่ไหน คือ ใกล้',
    'Cocktail - คุกเข่า',
    'Jaonaay - คนละชั้น',
    'MEYOU - ภาวนา',
    'Slot Machine - เคลิ้ม',
    'THE TOYS - ลาลาลอย (100%)',
    'atom chanakan - อ้าว',
    'WANYAi - เจ็บจนพอ (Enough)',
    'WANYAi - ลืมไป (Blind) [feat. ปู่จ๋าน ลองไมค์]',
    'Cocktail - เรา',
    'URBOYTJ - เป็นได้ทุกอย่าง',
    'Fymme Bongkot - กะทันหัน',
    'BOWKYLION - ลงใจ',
    'Getsunova - คนไม่จำเป็น',
    'KLEAR - จะรักหรือจะร้าย',
    'Getsunova - ความเงียบดังที่สุด',
    'Palmy - ซ่อนกลิ่น',
    'NONT TANONT - ทุกนาทีที่สวยงาม',
    'Pause - ดาว - Cover version',
    'Indigo - ถ้าฉันเป็นเขา',
    'Bedroom Audio - กอดไม่ได้',
    'Room 39 - เป็นทุกอย่าง',
    'ACTART - นอกจากชื่อฉัน',
    'NONT TANONT - วันครบเลิก',
    'Cocktail - เธอ',
    'Ice Sarunyu - คนใจง่าย',
    'F.HERO - จำเก่ง (Slipped Your Mind)',
    'Cocktail - ไม่เป็นรอง',
    'SCRUBB - ใกล้',
    'Palmy - คิดมาก',
    'Bodyslam - คิดฮอด',
    'Bedroom Audio - รักมือสอง',
    'F.HERO - มีแค่เรา',
    'D Gerrard - Luxury',
    '321 - มีอีกไหม '
]
